port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: false
  node_ip: 35.244.15.25
redis:
  address: localhost:6379
keys:
  APIVaniSelf887cf7c8: W3cYnN/seVvwnQsK/MWmYL9VcicIK5uz86FlkHTt7c8=
